image: node:8.12.0-alpine

stages:
  - publish-npm

.defaults: &defaults
  only:
    - master

before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

publish-package:
  <<: *defaults
  stage: publish-npm
  script:
    - npm install
    - npm run build
    - npm publish
